### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by ashishdandekar** [sosedoff/goodreads#24]
I haven't used Ruby ever. I am just trying to pull the Goodreads data from your app.
When I write require 'goodreads' on 'irb', it raises NameError saying uninitialized constant ActiveSupport.
I have no clue what is happening.

Would you let me know?

**Comment by sosedoff** [comment]
That seems to be a bug. I dont know what's the issue, havent used the library in years

**Comment by ashishdandekar** [comment]
So would you tell me a fix? I don't know what needs to be done. Had I known ruby well, I would have done it myself.

**Comment by sosedoff** [comment]
This issue is fixed. Please use 0.4.0
