### ISSUE TITLE
Should book.authors return an array?

### ISSUE THREAD

**Issue by rlgreen91** [sosedoff/goodreads#54]
I'm currently using `book_by_title` to get a book's info, and I'm confused as to why `book.authors` doesn't always return an array.  This way, the developers using the gem don't have to do any conditional checks when retrieving the data.  Was this a design decision for the gem, or is it due to how Goodreads returns data?  I couldn't tell when debugging.

**Comment by sosedoff** [comment]
Im not sure, maybe something has changed on Googreads API's side. Can you provide an example, specifically with the book data?
